#! /bin/sh

export AFEPACK_PATH="~/Packages/AFEPack"
export AFEPACK_TEMPLATE_PATH="$AFEPACK_PATH/template/tetrahedron"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/hfzhan/Packages/deal.II/lib

exec ./main $*

